### ISSUE TITLE
Is there any test environment?

### ISSUE THREAD

**Issue by hppRC** [Optimind-llc/fireclient#1]
Hi!! Thanks for making a great library!✨

I'd like to contribute this custom hooks, however it seems there is no testing libraries such as jest.
How can I contribute and ensure that the results ​are correct?
Or should I wait for later versions?

Thank you.

**Comment by TakaoNarikawa** [comment]
Thank you for commenting on this library.

Making test env is already in our todo 👍

Please wait for coming update.

Thanks.

**Comment by hppRC** [comment]
Yay!
I'll wait for update!!😳

Thanks.
